/*
 * Generates src/fonts.css: self-hosted IBM Plex @font-face rules with
 * font-display: optional, plus Capsize metric-matched fallback faces.
 *
 * Run from the repo root after bumping any @fontsource* package
 * (filenames / unicode-ranges can change between versions):
 *
 *   node scripts/genfonts.mjs
 *
 * See src/styles.css (which @imports the output) and src/routes/__root.tsx
 * (which preloads the matching woff2 via "?url").
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createFontStack } from "@capsizecss/core";
import ibmPlexSans from "@capsizecss/metrics/iBMPlexSans";
import ibmPlexSerif from "@capsizecss/metrics/iBMPlexSerif";
import ibmPlexMono from "@capsizecss/metrics/iBMPlexMono";
import arial from "@capsizecss/metrics/arial";
import georgia from "@capsizecss/metrics/georgia";
import courierNew from "@capsizecss/metrics/courierNew";

const NM = "node_modules";

// [fontsource CSS file, npm specifier used inside url()]
const SOURCES = [
  ["@fontsource-variable/ibm-plex-sans/wght.css", "@fontsource-variable/ibm-plex-sans"],
  ["@fontsource-variable/ibm-plex-sans/wght-italic.css", "@fontsource-variable/ibm-plex-sans"],
  ["@fontsource/ibm-plex-serif/400.css", "@fontsource/ibm-plex-serif"],
  ["@fontsource/ibm-plex-serif/500.css", "@fontsource/ibm-plex-serif"],
  ["@fontsource/ibm-plex-serif/600.css", "@fontsource/ibm-plex-serif"],
  ["@fontsource/ibm-plex-serif/700.css", "@fontsource/ibm-plex-serif"],
  ["@fontsource/ibm-plex-mono/400.css", "@fontsource/ibm-plex-mono"],
  ["@fontsource/ibm-plex-mono/700.css", "@fontsource/ibm-plex-mono"],
];

function transform(cssPath, pkg) {
  let css = readFileSync(`${NM}/${cssPath}`, "utf8");
  // The whole point: kill the swap-period flash.
  css = css.replace(/font-display:\s*swap;/g, "font-display: optional;");
  // Drop legacy .woff src (woff2 is universally supported) -> fewer emitted assets.
  css = css.replace(/,\s*url\(\.\/files\/[^)]*\.woff\)\s*format\('woff'\)/g, "");
  // Rewrite package-relative url() to a specifier Vite resolves + content-hashes,
  // deduping with the "?url" preload imports in __root.tsx.
  css = css.replace(/url\(\.\/files\/([^)]+)\)/g, (_m, f) => `url('${pkg}/files/${f}')`);
  return css.trim();
}

const realFaces = SOURCES.map(([f, pkg]) => transform(f, pkg)).join("\n\n");

function fallback(primary, fb) {
  return createFontStack([primary, fb], {
    fontFaceProperties: { fontDisplay: "swap" },
  }).fontFaces;
}

const fallbackFaces = [
  fallback(ibmPlexSans, arial),
  fallback(ibmPlexSerif, georgia),
  fallback(ibmPlexMono, courierNew),
].join("\n");

const header = `/*
 * GENERATED by scripts/genfonts.mjs — do not hand-edit; regenerate instead.
 *
 * fontsource bakes font-display:swap into every face, which forces a visible
 * fallback->webfont swap mid-load (the "font flash"). swap has an INFINITE swap
 * period and cannot be changed via a package flag, so we self-author the faces
 * here with font-display:optional — the only value with NO swap period, so the
 * browser never repaints text to the webfont after first paint.
 *
 * The url() specifiers are rewritten by Vite to the same content-hashed assets
 * that the rel=preload "?url" imports in __root.tsx use, so the preload is never
 * wasted (no double download).
 *
 * The "Fallback" faces are metric-matched (Capsize ascent/descent/line-gap/
 * size-adjust over Arial/Georgia/Courier New): on the rare cold load where the
 * webfont loses the ~100ms race and the fallback is kept, there is zero layout
 * shift and it looks ~identical to IBM Plex.
 */

`;

writeFileSync("src/fonts.css", header + fallbackFaces + "\n" + realFaces + "\n");

const count = (s, re) => (s.match(re) || []).length;
console.log("wrote src/fonts.css");
console.log("  real faces      :", count(realFaces, /@font-face/g));
console.log("  fallback faces  :", count(fallbackFaces, /@font-face/g));
console.log("  swap remaining  :", count(realFaces, /font-display:\s*swap/g), "(want 0)");
console.log("  legacy .woff    :", count(realFaces, /\.woff'\)/g), "(want 0)");
