/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImagesKeyRouteImport } from './routes/api.images.$key'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesKeyRoute = ApiImagesKeyRouteImport.update({
  id: '/api/images/$key',
  path: '/api/images/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/sign-in': typeof SignInRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/sign-in': typeof SignInRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/sign-in': typeof SignInRoute
  '/api/images/$key': typeof ApiImagesKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-account' | '/sign-in' | '/api/images/$key'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-account' | '/sign-in' | '/api/images/$key'
  id: '__root__' | '/' | '/create-account' | '/sign-in' | '/api/images/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateAccountRoute: typeof CreateAccountRoute
  SignInRoute: typeof SignInRoute
  ApiImagesKeyRoute: typeof ApiImagesKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$key': {
      id: '/api/images/$key'
      path: '/api/images/$key'
      fullPath: '/api/images/$key'
      preLoaderRoute: typeof ApiImagesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateAccountRoute: CreateAccountRoute,
  SignInRoute: SignInRoute,
  ApiImagesKeyRoute: ApiImagesKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
