/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetUpProfileRouteImport } from './routes/set-up-profile'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatingRatingSlugRouteImport } from './routes/rating/$ratingSlug'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUpProfileRoute = SetUpProfileRouteImport.update({
  id: '/set-up-profile',
  path: '/set-up-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRatingSlugRoute = RatingRatingSlugRouteImport.update({
  id: '/rating/$ratingSlug',
  path: '/rating/$ratingSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/set-up-profile': typeof SetUpProfileRoute
  '/sign-in': typeof SignInRoute
  '/rating/$ratingSlug': typeof RatingRatingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/set-up-profile': typeof SetUpProfileRoute
  '/sign-in': typeof SignInRoute
  '/rating/$ratingSlug': typeof RatingRatingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/set-up-profile': typeof SetUpProfileRoute
  '/sign-in': typeof SignInRoute
  '/rating/$ratingSlug': typeof RatingRatingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-account'
    | '/set-up-profile'
    | '/sign-in'
    | '/rating/$ratingSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-account'
    | '/set-up-profile'
    | '/sign-in'
    | '/rating/$ratingSlug'
  id:
    | '__root__'
    | '/'
    | '/create-account'
    | '/set-up-profile'
    | '/sign-in'
    | '/rating/$ratingSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateAccountRoute: typeof CreateAccountRoute
  SetUpProfileRoute: typeof SetUpProfileRoute
  SignInRoute: typeof SignInRoute
  RatingRatingSlugRoute: typeof RatingRatingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-up-profile': {
      id: '/set-up-profile'
      path: '/set-up-profile'
      fullPath: '/set-up-profile'
      preLoaderRoute: typeof SetUpProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/$ratingSlug': {
      id: '/rating/$ratingSlug'
      path: '/rating/$ratingSlug'
      fullPath: '/rating/$ratingSlug'
      preLoaderRoute: typeof RatingRatingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateAccountRoute: CreateAccountRoute,
  SetUpProfileRoute: SetUpProfileRoute,
  SignInRoute: SignInRoute,
  RatingRatingSlugRoute: RatingRatingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
