/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as StuffStuffSlugRouteImport } from './routes/stuff/$stuffSlug'
import { Route as RatingRatingSlugRouteImport } from './routes/rating/$ratingSlug'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSetUpProfileRouteImport } from './routes/_auth/set-up-profile'
import { Route as AuthCreateAccountRouteImport } from './routes/_auth/create-account'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StuffStuffSlugRoute = StuffStuffSlugRouteImport.update({
  id: '/stuff/$stuffSlug',
  path: '/stuff/$stuffSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRatingSlugRoute = RatingRatingSlugRouteImport.update({
  id: '/rating/$ratingSlug',
  path: '/rating/$ratingSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetUpProfileRoute = AuthSetUpProfileRouteImport.update({
  id: '/set-up-profile',
  path: '/set-up-profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateAccountRoute = AuthCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/create-account': typeof AuthCreateAccountRoute
  '/set-up-profile': typeof AuthSetUpProfileRoute
  '/sign-in': typeof AuthSignInRoute
  '/rating/$ratingSlug': typeof RatingRatingSlugRoute
  '/stuff/$stuffSlug': typeof StuffStuffSlugRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/create-account': typeof AuthCreateAccountRoute
  '/set-up-profile': typeof AuthSetUpProfileRoute
  '/sign-in': typeof AuthSignInRoute
  '/rating/$ratingSlug': typeof RatingRatingSlugRoute
  '/stuff/$stuffSlug': typeof StuffStuffSlugRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_auth/create-account': typeof AuthCreateAccountRoute
  '/_auth/set-up-profile': typeof AuthSetUpProfileRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/rating/$ratingSlug': typeof RatingRatingSlugRoute
  '/stuff/$stuffSlug': typeof StuffStuffSlugRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/create-account'
    | '/set-up-profile'
    | '/sign-in'
    | '/rating/$ratingSlug'
    | '/stuff/$stuffSlug'
    | '/user/$username'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/create-account'
    | '/set-up-profile'
    | '/sign-in'
    | '/rating/$ratingSlug'
    | '/stuff/$stuffSlug'
    | '/user/$username'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/privacy'
    | '/terms'
    | '/_auth/create-account'
    | '/_auth/set-up-profile'
    | '/_auth/sign-in'
    | '/rating/$ratingSlug'
    | '/stuff/$stuffSlug'
    | '/user/$username'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  RatingRatingSlugRoute: typeof RatingRatingSlugRoute
  StuffStuffSlugRoute: typeof StuffStuffSlugRoute
  UserUsernameRoute: typeof UserUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stuff/$stuffSlug': {
      id: '/stuff/$stuffSlug'
      path: '/stuff/$stuffSlug'
      fullPath: '/stuff/$stuffSlug'
      preLoaderRoute: typeof StuffStuffSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/$ratingSlug': {
      id: '/rating/$ratingSlug'
      path: '/rating/$ratingSlug'
      fullPath: '/rating/$ratingSlug'
      preLoaderRoute: typeof RatingRatingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/set-up-profile': {
      id: '/_auth/set-up-profile'
      path: '/set-up-profile'
      fullPath: '/set-up-profile'
      preLoaderRoute: typeof AuthSetUpProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/create-account': {
      id: '/_auth/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof AuthCreateAccountRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute
  AuthSetUpProfileRoute: typeof AuthSetUpProfileRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthSetUpProfileRoute: AuthSetUpProfileRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  RatingRatingSlugRoute: RatingRatingSlugRoute,
  StuffStuffSlugRoute: StuffStuffSlugRoute,
  UserUsernameRoute: UserUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
